### ISSUE TITLE
Add icons

### ISSUE THREAD

**Issue by budparr** [theNewDynamic/hugo-module-tnd-events#3]
<img width="314" alt="Screen Shot 2022-07-05 at 12 04 30 PM" src="https://user-images.githubusercontent.com/115347/177370216-eb1e6fd5-53ef-4205-8969-be6dc5c6972e.png">

**Comment by regisphilibert** [comment]
Just did. I added the built in icons (monocrhome). The module does have them but we don't use them.

**Comment by regisphilibert** [comment]
@budparr I did that on retroreport by mistake. Do you want me to revert?

**Comment by budparr** [comment]
having it on retro report is fine. anyway to use colors? Also, with the icons on there I'd like to change the padding. Happy to do that, if you point me to the right file

**Comment by regisphilibert** [comment]
For colors, it's just about finding the proper SVGs, any idea?

**Comment by budparr** [comment]
https://cdn.addevent.com/libs/imgs/icon-google-t5.svg
https://cdn.addevent.com/libs/imgs/icon-apple-t5.svg
https://cdn.addevent.com/libs/imgs/icon-outlook-t5.svg
https://cdn.addevent.com/libs/imgs/icon-yahoo-t5.svg

via https://www.addevent.com/documentation/add-to-calendar-button

**Comment by budparr** [comment]
@regisphilibert I updated the RR add-to-cal and it's pretty much how it should be on every implementation as the default. The only difference would be that when it's more stand-alone (like underneath some text) it would have a border around the copy/icon.

**Comment by budparr** [comment]
can we close this, or does it still need to be done for the module?

**Comment by regisphilibert** [comment]
Yes we can close, this is been done on the events module already if I'm not mistaken: https://github.com/theNewDynamic/hugo-module-tnd-events/commit/e6ac6a7f7a0ab9258520869dcee2027f5e7b3c77
